cp acbusform.u acbusform.u.old 
cp aclineform.u aclineform.u.old 
cp areaselect.u areaselect.u.old 
cp bus_icon.u bus_icon.u.old 
cp buscoord.u buscoord.u.old 
cp buseditn.u buseditn.u.old 
cp bushelp.u bushelp.u.old 
cp buslistdia.u buslistdia.u.old 
cp bussectn.u bussectn.u.old 
cp cflow.u cflow.u.old 
cp color.u color.u.old 
cp contbusdia.u contbusdia.u.old 
cp contform.u contform.u.old 
cp dcbusform.u dcbusform.u.old 
cp dclineform.u dclineform.u.old 
cp debug_dmgr.u debug_dmgr.u.old 
cp define.u define.u.old 
cp display.u display.u.old 
cp equivform.u equivform.u.old 
cp fopendia.u fopendia.u.old 
cp frontdia.u frontdia.u.old 
cp fsavedia.u fsavedia.u.old 
cp help.u help.u.old 
cp icons.u icons.u.old 
cp ipcwindow.u ipcwindow.u.old 
cp ipfreport.u ipfreport.u.old 
cp linedia.u linedia.u.old 
cp linetap.u linetap.u.old 
cp linetap2.u linetap2.u.old 
cp linezcalc.u linezcalc.u.old 
cp main.u main.u.old 
cp menu_bar.u menu_bar.u.old 
cp networkedt.u networkedt.u.old 
cp pf_descrip.u pf_descrip.u.old 
cp pixmaps.u pixmaps.u.old 
cp pqcrvform.u pqcrvform.u.old 
cp printopt.u printopt.u.old 
cp procs.u procs.u.old 
cp recorddia.u recorddia.u.old 
cp regxfmr.u regxfmr.u.old 
cp reportdia.u reportdia.u.old 
cp solve.u solve.u.old 
cp statdia.u statdia.u.old 
cp swrreac.u swrreac.u.old 
cp systemtest.u systemtest.u.old 
cp tools.u tools.u.old 
cp values.u values.u.old 
cp viewmenu.u viewmenu.u.old 
cp xfmrdia.u xfmrdia.u.old 
