c  brtype.inc
 
      integer BRTYP_PEQ, BRTYP_LM, BRTYP_L,  BRTYP_R , BRTYP_T, 
     1        BRTYP_TP , BRTYP_LD, BRTYP_E,  BRTYP_RZ
 
      parameter ( BRTYP_PEQ = 1 )
      parameter ( BRTYP_LM  = 2 )
      parameter ( BRTYP_L   = 3 )
      parameter ( BRTYP_R   = 4 )
      parameter ( BRTYP_T   = 5 )
      parameter ( BRTYP_TP  = 6 )
      parameter ( BRTYP_LD  = 7 )
      parameter ( BRTYP_E   = 8 )
      parameter ( BRTYP_RZ  = 9 ) 

