#include <stddef.h>
#include "ft.h"
#include "cflowlib.h"

/* !!!!!! field table records must be in same order as enum !!!!!!! */
 
struct fld_table _ft[MAXRECNUM][MAXFIELDNUM]={
{{ PF_REC,0,sizeof(pf_rec),0,0},
},
{{ AC_BUS,0,sizeof(pf_AC_bus),0,80 },
 { 's', offsetof(pf_AC_bus,type),                  2,   0,  2, 0},
 { 's', offsetof(pf_AC_bus,owner),                 3,   3,  3, 0},
 { 's', offsetof(pf_AC_bus,name),                  8,   6,  8, 0},
 { 'f', offsetof(pf_AC_bus,kv),        sizeof(float),  14,  4, 0},
 { 's', offsetof(pf_AC_bus,zone),                  2,  18,  2, 0},
 { 'f', offsetof(pf_AC_bus,Pload),     sizeof(float),  20,  5, 0},
 { 'f', offsetof(pf_AC_bus,Qload),     sizeof(float),  25,  5, 0},
 { 'f', offsetof(pf_AC_bus,Pshunt),    sizeof(float),  30,  4, 0},
 { 'f', offsetof(pf_AC_bus,Qshunt),    sizeof(float),  34,  4, 0},
 { 'f', offsetof(pf_AC_bus,Pmax),      sizeof(float),  38,  4, 0},
 { 'f', offsetof(pf_AC_bus,Pgen),      sizeof(float),  42,  5, 0},
 { 'f', offsetof(pf_AC_bus,Qsch_Qmax), sizeof(float),  47,  5, 0},
 { 'f', offsetof(pf_AC_bus,Qmin),      sizeof(float),  52,  5, 0},
 { 'f', offsetof(pf_AC_bus,Vhold_Vmax),sizeof(float),  57,  4, 3},
 { 'f', offsetof(pf_AC_bus,Vmin_Vdeg), sizeof(float),  61,  4, 3},
 { 's', offsetof(pf_AC_bus,rmt_name),              8,  65,  8, 0},
 { 'f', offsetof(pf_AC_bus,rmt_kv),    sizeof(float),  73,  4, 0},
 { 'f', offsetof(pf_AC_bus,pct_vars),  sizeof(float),  77,  3, 0},
},
{{ LD_LINE, 0, sizeof(pf_LD),0,88 },
 { 's', offsetof(pf_LD,type),                      2,   0,  2, 0},
 { 's', offsetof(pf_LD,owner),                     3,   3,  3, 0},
 { 's', offsetof(pf_LD,bus1_name),                 8,   6,  8, 0},
 { 'f', offsetof(pf_LD,bus1_kv),       sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_LD,meter),          sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_LD,bus2_name),                 8,  19,  8, 0},
 { 'f', offsetof(pf_LD,bus2_kv),       sizeof(float),  27,  4, 0},
 { 's', offsetof(pf_LD,I_or_R_control),            1,  55,  1, 0},
 { 'f', offsetof(pf_LD,total_rating),  sizeof(float),  33,  4, 0},
 { 'f', offsetof(pf_LD,R),             sizeof(float),  37,  6, 2},
 { 'f', offsetof(pf_LD,L_mh),          sizeof(float),  43,  6, 2},
 { 'f', offsetof(pf_LD,C_uf),          sizeof(float),  49,  6, 2},
 { 'f', offsetof(pf_LD,P_sched),       sizeof(float),  56,  5, 1},
 { 'f', offsetof(pf_LD,V_sched),       sizeof(float),  61,  5, 1},
 { 'f', offsetof(pf_LD,miles),         sizeof(float),  66,  4, 1},
 { 'f', offsetof(pf_LD,alpha_N_deg),   sizeof(float),  70,  4, 1},
 { 'f', offsetof(pf_LD,gamma_0_deg),   sizeof(float),  74,  4, 0},
 { 'f', offsetof(pf_LD,thermal_rating),sizeof(float),  80,  4, 0},
 { 'f', offsetof(pf_LD,bottleneck_rating),sizeof(float),84, 4, 0},
},
{{ LM_LINE, 0, sizeof(pf_LM),0,88 },
 { 's', offsetof(pf_LM,type),                      2,   0,  2, 0},
 { 's', offsetof(pf_LM,owner),                     3,   3,  3, 0},
 { 's', offsetof(pf_LM,bus1_name),                 8,   6,  8, 0},
 { 'f', offsetof(pf_LM,bus1_kv),       sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_LM,meter),          sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_LM,bus2_name),                 8,  19,  8, 0},
 { 'f', offsetof(pf_LM,bus2_kv),       sizeof(float),  27,  4, 0},
 { 'f', offsetof(pf_LM,total_rating),  sizeof(float),  33,  4, 0},
 { 'f', offsetof(pf_LM,R),             sizeof(float),  37,  6, 2},
 { 'f', offsetof(pf_LM,L_mh),          sizeof(float),  43,  6, 2},
 { 'f', offsetof(pf_LM,C_uf),          sizeof(float),  49,  6, 2},
 { 'f', offsetof(pf_LM,miles),         sizeof(float),  70,  4, 0},
 { 's', offsetof(pf_LM,date_in),                   3,  74,  3, 0},
 { 's', offsetof(pf_LM,date_out),                  3,  77,  3, 0},
 { 'f', offsetof(pf_LM,thermal_rating),sizeof(float),  80,  4, 0},
 { 'f', offsetof(pf_LM,bottleneck_rating),sizeof(float),84, 4, 0},
},
{{ E_LINE, 0, sizeof(pf_E),0,88 },   
 { 's', offsetof(pf_E,type),                       2,   0,  2, 0},
 { 's', offsetof(pf_E,owner),                      3,   3,  3, 0},
 { 's', offsetof(pf_E,bus1_name),                  8,   6,  8, 0},
 { 'f', offsetof(pf_E,bus1_kv),        sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_E,meter),           sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_E,bus2_name),                  8,  19,  8, 0},
 { 'f', offsetof(pf_E,bus2_kv),        sizeof(float),  27,  4, 0},
 { 's', offsetof(pf_E,ckt_id),                     1,  31,  1, 0},
 { 'l', offsetof(pf_E,section),         sizeof(long),  32,  1, 0},
 { 'f', offsetof(pf_E,total_rating),   sizeof(float),  33,  4, 0},
 { 'l', offsetof(pf_E,num_ckts),        sizeof(long),  37,  1, 0},
 { 'f', offsetof(pf_E,r),              sizeof(float),  38,  6, 5},
 { 'f', offsetof(pf_E,x),              sizeof(float),  44,  6, 5},
 { 'f', offsetof(pf_E,g1),             sizeof(float),  50,  6, 5},
 { 'f', offsetof(pf_E,b1),             sizeof(float),  56,  6, 5},
 { 'f', offsetof(pf_E,g2),             sizeof(float),  62,  6, 5},
 { 'f', offsetof(pf_E,b2),             sizeof(float),  68,  6, 5},
 { 's', offsetof(pf_E,date_in),                    3,  74,  3, 0},
 { 's', offsetof(pf_E,date_out),                   3,  77,  3, 0},
 { 'f', offsetof(pf_E,thermal_rating), sizeof(float),  80,  4, 0},
 { 'f', offsetof(pf_L,bottleneck_rating),sizeof(float),84,  4, 0},
},
{{ L_LINE, 0, sizeof(pf_L),0, 88 },
 { 's', offsetof(pf_L,type),                       2,   0,  2, 0},
 { 's', offsetof(pf_L,owner),                      3,   3,  3, 0},
 { 's', offsetof(pf_L,bus1_name),                  8,   6,  8, 0},
 { 'f', offsetof(pf_L,bus1_kv),        sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_L,meter),           sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_L,bus2_name),                  8,  19,  8, 0},
 { 'f', offsetof(pf_L,bus2_kv),        sizeof(float),  27,  4, 0},
 { 's', offsetof(pf_L,ckt_id),                     1,  31,  1, 0},
 { 'l', offsetof(pf_L,section),         sizeof(long),  32,  1, 0},
 { 'f', offsetof(pf_L,total_rating),   sizeof(float),  33,  4, 0},
 { 'l', offsetof(pf_L,num_ckts),        sizeof(long),  37,  1, 0},
 { 'f', offsetof(pf_L,r),              sizeof(float),  38,  6, 5},
 { 'f', offsetof(pf_L,x),              sizeof(float),  44,  6, 5},
 { 'f', offsetof(pf_L,g),              sizeof(float),  50,  6, 5},
 { 'f', offsetof(pf_L,b),              sizeof(float),  56,  6, 5},
 { 'f', offsetof(pf_L,miles),          sizeof(float),  62,  4, 1},
 { 's', offsetof(pf_L,descrip),                    8,  66,  8, 0},
 { 's', offsetof(pf_L,date_in),                    3,  74,  3, 0},
 { 's', offsetof(pf_L,date_out),                   3,  77,  3, 0},
 { 'f', offsetof(pf_L,thermal_rating), sizeof(float),  80,  4, 0},
 { 'f', offsetof(pf_L,bottleneck_rating),sizeof(float),84,  4, 0},
},
{{ T_LINE, 0, sizeof(pf_T),0, 92 },
 { 's', offsetof(pf_T,type),                       2,   0,  2, 0},
 { 's', offsetof(pf_T,owner),                      3,   3,  3, 0},
 { 's', offsetof(pf_T,bus1_name),                  8,   6,  8, 0},
 { 'f', offsetof(pf_T,bus1_kv),        sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_T,meter),           sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_T,bus2_name),                  8,  19,  8, 0},
 { 'f', offsetof(pf_T,bus2_kv),        sizeof(float),  27,  4, 0},
 { 's', offsetof(pf_T,ckt_id),                     1,  31,  1, 0},
 { 'l', offsetof(pf_T,section),         sizeof(long),  32,  1, 0},
 { 'f', offsetof(pf_T,total_rating),   sizeof(float),  33,  4, 0},
 { 'l', offsetof(pf_T,num_ckts),        sizeof(long),  37,  1, 0},
 { 'f', offsetof(pf_T,r),              sizeof(float),  38,  6, 5},
 { 'f', offsetof(pf_T,x),              sizeof(float),  44,  6, 5},
 { 'f', offsetof(pf_T,g),              sizeof(float),  50,  6, 5},
 { 'f', offsetof(pf_T,b),              sizeof(float),  56,  6, 5},
 { 'f', offsetof(pf_T,tap1),           sizeof(float),  62,  5, 2}, 
 { 'f', offsetof(pf_T,tap2),           sizeof(float),  67,  5, 2},  
 { 's', offsetof(pf_T,date_in),                    3,  74,  3, 0},
 { 's', offsetof(pf_T,date_out),                   3,  77,  3, 0},
 { 'f', offsetof(pf_T,thermal_rating), sizeof(float),  80,  4, 0},
 { 'f', offsetof(pf_T,bottleneck_rating),sizeof(float),88,  4, 0},
 { 'f', offsetof(pf_T,emergency_rating),sizeof(float), 84,  4, 0},
},
{{ TP_LINE, 0, sizeof(pf_TP),0, 92 },
 { 's', offsetof(pf_TP,type),                      2,   0,  2, 0},
 { 's', offsetof(pf_TP,owner),                     3,   3,  3, 0},
 { 's', offsetof(pf_TP,bus1_name),                 8,   6,  8, 0},
 { 'f', offsetof(pf_TP,bus1_kv),       sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_TP,meter),          sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_TP,bus2_name),                 8,  19,  8, 0},
 { 'f', offsetof(pf_TP,bus2_kv),       sizeof(float),  27,  4, 0},
 { 's', offsetof(pf_TP,ckt_id),                    1,  31,  1, 0},
 { 'l', offsetof(pf_TP,section),       sizeof(long),   32,  1, 0},
 { 'f', offsetof(pf_TP,total_rating),  sizeof(float),  33,  4, 0},
 { 'l', offsetof(pf_TP,num_ckts),      sizeof(long),   37,  1, 0},
 { 'f', offsetof(pf_TP,r),             sizeof(float),  38,  6, 5},
 { 'f', offsetof(pf_TP,x),             sizeof(float),  44,  6, 5},
 { 'f', offsetof(pf_TP,g),             sizeof(float),  50,  6, 5},
 { 'f', offsetof(pf_TP,b),             sizeof(float),  56,  6, 5},
 { 'f', offsetof(pf_TP,phase_shift_deg),sizeof(float), 62,  5, 2}, 
 { 'f', offsetof(pf_TP,tap2),          sizeof(float),  67,  5, 2},  
 { 's', offsetof(pf_TP,date_in),                   3,  74,  3, 0},
 { 's', offsetof(pf_TP,date_out),                  3,  77,  3, 0},
 { 'f', offsetof(pf_TP,thermal_rating),sizeof(float),  80,  4, 0},
 { 'f', offsetof(pf_TP,bottleneck_rating),sizeof(float),88, 4, 0},
 { 'f', offsetof(pf_TP,emergency_rating),sizeof(float),84,  4, 0},
},
{{ R_LINE, 0, sizeof(pf_R),0, 80},  
 { 's', offsetof(pf_R,type),                       2,   0,  2, 0},
 { 's', offsetof(pf_R,owner),                      3,   3,  3, 0},
 { 's', offsetof(pf_R,bus1_name),                  8,   6,  8, 0},
 { 'f', offsetof(pf_R,bus1_kv),        sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_R,var_tap_side),    sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_R,bus2_name),                  8,  19,  8, 0},
 { 'f', offsetof(pf_R,bus2_kv),        sizeof(float),  27,  4, 0},
 { 'l', offsetof(pf_R,num_taps),        sizeof(long),  55,  2, 0},  
 { 'f', offsetof(pf_R,max_tap),        sizeof(float),  45,  5, 2},
 { 'f', offsetof(pf_R,min_tap),        sizeof(float),  50,  5, 2},
 { 's', offsetof(pf_R,rmt_bus_name),               8,  33,  8, 0},
 { 's', offsetof(pf_R,date_in),                    3,  74,  3, 0},
 { 's', offsetof(pf_R,date_out),                   3,  77,  3, 0},
 { 'f', offsetof(pf_R,rmt_bus_kv),     sizeof(float),  41,  4, 0},
 { 'f', offsetof(pf_R,Qmax),           sizeof(float),  57,  5, 0},
 { 'f', offsetof(pf_R,Qmin),           sizeof(float),  62,  5, 0},
},
{{RM_LINE, 0, sizeof(pf_RM), 0, 80},
 { 's', offsetof(pf_RM,type),                      2,   0,  2, 0},
 { 's', offsetof(pf_RM,owner),                     3,   3,  3, 0},
 { 's', offsetof(pf_RM,bus1_name),                 8,   6,  8, 0},
 { 'f', offsetof(pf_RM,bus1_kv),       sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_RM,var_tap_side),   sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_RM,bus2_name),                 8,  19,  8, 0},
 { 'f', offsetof(pf_RM,bus2_kv),       sizeof(float),  27,  4, 0},
 { 'l', offsetof(pf_RM,num_taps),       sizeof(long),  55,  2, 0},  
 { 'f', offsetof(pf_RM,max_phase_shift_deg),sizeof(float),  45,  5, 2},
 { 'f', offsetof(pf_RM,min_phase_shift_deg),sizeof(float),  50,  5, 2},
 { 's', offsetof(pf_RM,rmt_bus_name),              8,  33,  8, 0},
 { 's', offsetof(pf_RM,date_in),                   3,  74,  3, 0},
 { 's', offsetof(pf_RM,date_out),                  3,  77,  3, 0},
 { 'f', offsetof(pf_RM,rmt_bus_kv),    sizeof(float),  41,  4, 0},
 { 'f', offsetof(pf_RM,Pmax),          sizeof(float),  57,  5, 0},
 { 'f', offsetof(pf_RM,Pmin),          sizeof(float),  62,  5, 0},
},
{{RZ_LINE, 0, sizeof(pf_RZ), 0, 72},
 { 's', offsetof(pf_RZ,type),                      2,   0,  2, 0},
 { 's', offsetof(pf_RZ,owner),                     3,   2,  1, 0},
 { 's', offsetof(pf_RZ,bus1_name),                 8,   6,  8, 0},
 { 'f', offsetof(pf_RZ,bus1_kv),       sizeof(float),  14,  4, 0},
 { 'l', offsetof(pf_RZ,var_tap_side),   sizeof(long),  18,  1, 0},
 { 's', offsetof(pf_RZ,bus2_name),                 8,  19,  8, 0},
 { 'f', offsetof(pf_RZ,bus2_kv),       sizeof(float),  27,  4, 0},
 { 's', offsetof(pf_RZ,ckt_id),                    1,  31,  1, 0},
 { 'l', offsetof(pf_RZ,section),        sizeof(long),  32,  1, 0},
 { 'f', offsetof(pf_RZ,I_rate),        sizeof(float),  44,  4, 0},
 { 'l', offsetof(pf_RZ,rani_type),      sizeof(long),  33,  1, 0},
 { 'f', offsetof(pf_RZ,Pc_max),        sizeof(float),  34,  5, 0},
 { 'f', offsetof(pf_RZ,Pc_min),        sizeof(float),  39,  5, 0},
 { 'f', offsetof(pf_RZ,Xij_max),       sizeof(float),  48,  6, 5},
 { 'f', offsetof(pf_RZ,Xij_min),       sizeof(float),  54,  6, 5},
 { 'f', offsetof(pf_RZ,Bis_max),       sizeof(float),  60,  6, 5},
 { 'f', offsetof(pf_RZ,Bis_min),       sizeof(float),  66,  6, 5},
}, 

{{AC_SOLN, 0, sizeof(pf_bus_AC_soln), 0, 215},
 {'f', offsetof(pf_bus_AC_soln,Pgen),  sizeof(float),  20, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Qgen),  sizeof(float),  35, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Vmag),  sizeof(float),  50, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Vdeg),  sizeof(float),  65, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Pload), sizeof(float),  80, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Qload), sizeof(float),  95, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Bshunt_used),    sizeof(float), 110, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Bshunt_sch),     sizeof(float), 125, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Bshunt_used_cap),sizeof(float), 140, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Bshunt_sch_cap), sizeof(float), 155, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Bshunt_used_rx), sizeof(float), 170, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Bshunt_sch_rx),  sizeof(float), 185, 15, 7},
 {'f', offsetof(pf_bus_AC_soln,Qunsch),         sizeof(float), 200, 15, 7},
},

{{DC_SOLN, 0, sizeof(pf_bus_DC_soln), 0, 110},
 {'f', offsetof(pf_bus_DC_soln,P_DC),           sizeof(float),  20, 15, 7},
 {'f', offsetof(pf_bus_DC_soln,Q_DC),           sizeof(float),  35, 15, 7},
 {'f', offsetof(pf_bus_DC_soln,V_DC),           sizeof(float),  50, 15, 7},
 {'f', offsetof(pf_bus_DC_soln,converter_deg),  sizeof(float),  65, 15, 7},
 {'f', offsetof(pf_bus_DC_soln,P_valve_losses), sizeof(float),  80, 15, 7},
 {'f', offsetof(pf_bus_DC_soln,Q_valve_losses), sizeof(float),  95, 15, 7},
},

{{DC_BUS, 0, sizeof(pf_DC_bus), 0, 80},
 {'s', offsetof(pf_DC_bus,type),                      2,   0,  2, 0},
 {'s', offsetof(pf_DC_bus,owner),                     3,   3,  3, 0},
 {'s', offsetof(pf_DC_bus,name),                      8,   6,  8, 0},
 {'f', offsetof(pf_DC_bus,kv),            sizeof(float),  14,  4, 0},
 {'s', offsetof(pf_DC_bus,zone),                      2,  18,  2, 0},
 {'l', offsetof(pf_DC_bus,bridges_per_ckt),sizeof(long),  23,  2, 0},
 {'f', offsetof(pf_DC_bus,smooth_rx_mh),  sizeof(float),  25,  5, 1},
 {'f', offsetof(pf_DC_bus,alpha_min_deg), sizeof(float),  30,  5, 1},
 {'f', offsetof(pf_DC_bus,alpha_stop_deg),sizeof(float),  35,  5, 1},
 {'f', offsetof(pf_DC_bus,valve_drop_per_bridge_volts),sizeof(float), 40, 5, 1},
 {'f', offsetof(pf_DC_bus,bridge_current_rating_amps), sizeof(float), 45, 5, 1},
 {'f', offsetof(pf_DC_bus,alpha_gamma_N_deg),sizeof(float),63, 3, 1},
 {'f', offsetof(pf_DC_bus,gamma_0_deg),   sizeof(float),  66,  3, 1},
 {'f', offsetof(pf_DC_bus,P_sched),       sizeof(float),  69,  6, 1},   
 {'f', offsetof(pf_DC_bus,V_sched),       sizeof(float),  75,  5, 1},
 {'s', offsetof(pf_DC_bus,commutating_bus_name),      8,  50,  8, 0},
 {'f', offsetof(pf_DC_bus,commutating_bus_kv),sizeof(float),58, 4,0},
 {'s', offsetof(pf_DC_bus,converter_code),            1,  62,  1, 0},
},

{{BRANCH_SOLN, 0, sizeof(pf_branch_soln), 0, 249},
 {'l', offsetof(pf_branch_soln,num_ckts),  sizeof(long),  32,  1, 0},
 {'f', offsetof(pf_branch_soln,Pin),      sizeof(float),  33, 15, 7},
 {'f', offsetof(pf_branch_soln,Qin),      sizeof(float),  48, 15, 7},
 {'f', offsetof(pf_branch_soln,Pout),     sizeof(float),  63, 15, 7},
 {'f', offsetof(pf_branch_soln,Qout),     sizeof(float),  78, 15, 7},
 {'f', offsetof(pf_branch_soln,Ploss),    sizeof(float),  93, 15, 7},
 {'f', offsetof(pf_branch_soln,Qloss),    sizeof(float), 108, 15, 7},
 {'f', offsetof(pf_branch_soln,crit_line_load_amps),sizeof(float), 123, 15, 7},
 {'f', offsetof(pf_branch_soln,crit_line_rat_amps), sizeof(float), 138,  8, 1},
 {'s', offsetof(pf_branch_soln,crit_line_rat_code),             1, 146,  1, 0},
 {'l', offsetof(pf_branch_soln,crit_line_load_term), sizeof(long), 147,  1, 0},
 {'f', offsetof(pf_branch_soln,crit_xfmr_load_mva), sizeof(float), 148, 15, 7},
 {'f', offsetof(pf_branch_soln,crit_xfmr_rat_mva),  sizeof(float), 163,  8, 1},
 {'s', offsetof(pf_branch_soln,crit_xfmr_rat_code),             1, 171,  1, 0},
 {'l', offsetof(pf_branch_soln,crit_xfmr_load_term), sizeof(long), 172,  1, 0},
 {'f', offsetof(pf_branch_soln,tot_line_load_pct),  sizeof(float), 173, 15, 7},
 {'f', offsetof(pf_branch_soln,tot_line_load_amps), sizeof(float), 188, 15, 7},
 {'f', offsetof(pf_branch_soln,tot_xfmr_load_pct),  sizeof(float), 203, 15, 7},
 {'f', offsetof(pf_branch_soln,tot_xfmr_load_mva),  sizeof(float), 218, 15, 7},
 {'f', offsetof(pf_branch_soln,tap1),     sizeof(float), 233,  8, 2},
 {'f', offsetof(pf_branch_soln,tap2),     sizeof(float), 241,  8, 2},
},

{{BRANCH, 0, sizeof(pf_branch), 0, 88},
 {'s', offsetof(pf_branch,type),                      2,   0,  2, 0},
 {'s', offsetof(pf_branch,owner),                     3,   3,  3, 0},
 {'s', offsetof(pf_branch,bus1_name),                 8,   6,  8, 0},
 {'f', offsetof(pf_branch,bus1_kv),       sizeof(float),  14,  4, 0},
 {'l', offsetof(pf_branch,meter),          sizeof(long),  18,  1, 0},
 {'s', offsetof(pf_branch,bus2_name),                 8,  19,  8, 0},
 {'f', offsetof(pf_branch,bus2_kv),       sizeof(float),  27,  4, 0},
 {'s', offsetof(pf_branch,ckt_id),                    1,  31,  1, 0},
 {'l', offsetof(pf_branch,section),        sizeof(long),  32,  1, 0},
 {'f', offsetof(pf_branch,total_rating),  sizeof(float),  33,  4, 0},
 {'l', offsetof(pf_branch,num_ckts),       sizeof(long),  37,  1, 0},
 {'f', offsetof(pf_branch,r),             sizeof(float),  38,  6, 5},
 {'f', offsetof(pf_branch,x),             sizeof(float),  44,  6, 5},
 {'f', offsetof(pf_branch,g),             sizeof(float),  50,  6, 5},
 {'f', offsetof(pf_branch,b),             sizeof(float),  56,  6, 5},
 {'s', offsetof(pf_branch,descrip),                   8,  66,  8, 0},
 {'s', offsetof(pf_branch,date_in),                   3,  74,  3, 0},
 {'s', offsetof(pf_branch,date_out),                  3,  77,  3, 0},
 {'f', offsetof(pf_branch,thermal_rating),sizeof(float),  80,  4, 0},
 {'f', offsetof(pf_branch,emergency_rating),sizeof(float),84,  4, 0},
},
{{AREA_SOLN, 0, sizeof(pf_area_soln), 0, 73},
 {'f', offsetof(pf_area_soln,Pgen),       sizeof(float), 13, 15,  7},
 {'f', offsetof(pf_area_soln,Pload),      sizeof(float), 28, 15,  7},
 {'f', offsetof(pf_area_soln,Ploss),      sizeof(float), 43, 15,  7},
 {'f', offsetof(pf_area_soln,Pexport),    sizeof(float), 58, 15,  7},
},

{{AREA, 0,  sizeof(pf_area),  0, 80},
 {'s', offsetof(pf_area,type),                    2,       0,  2, 0},
 {'s', offsetof(pf_area,name),                   10,       3, 10, 0},
 {'s', offsetof(pf_area,sbus_name),               8,      13,  8, 0},
 {'f', offsetof(pf_area,sbus_kv),         sizeof(float),  21,  4, 0},
 {'f', offsetof(pf_area,sched_export),    sizeof(float),  26,  8, 0},
 {'s', offsetof(pf_area,zone0),                   2,      35,  2, 0},
 {'s', offsetof(pf_area,zone1),                   2,      38,  2, 0},
 {'s', offsetof(pf_area,zone2),                   2,      41,  2, 0},
 {'s', offsetof(pf_area,zone3),                   2,      44,  2, 0},
 {'s', offsetof(pf_area,zone4),                   2,      47,  2, 0},
 {'s', offsetof(pf_area,zone5),                   2,      50,  2, 0},
 {'s', offsetof(pf_area,zone6),                   2,      53,  2, 0},
 {'s', offsetof(pf_area,zone7),                   2,      56,  2, 0},
 {'s', offsetof(pf_area,zone8),                   2,      59,  2, 0},
 {'s', offsetof(pf_area,zone9),                   2,      62,  2, 0},
 {'f', offsetof(pf_area,max_Vpu),         sizeof(float),  72,  4, 0},
 {'f', offsetof(pf_area,min_Vpu),         sizeof(float),  76,  4, 0},
},

{{ITIE_SOLN, 0, sizeof(pf_itie_soln), 0,  71},
 {'f', offsetof(pf_itie_soln,Pexport),    sizeof(float),  39, 15, 7},
 {'f', offsetof(pf_itie_soln,Pcirc),      sizeof(float),  54, 15, 7},
 {'l', offsetof(pf_itie_soln,input_exists),sizeof(long),  70,  1, 0},
},

{{ITIE, 0, sizeof(pf_itie), 0, 39},
 {'s', offsetof(pf_itie,type),                        2,   0,  2, 0},
 {'s', offsetof(pf_itie,area1_name),                 10,   3, 10, 0},
 {'s', offsetof(pf_itie,area2_name),                 10,  14, 10, 0},
 {'f', offsetof(pf_itie,sched_export),    sizeof(float),  24, 15, 7},
},

{{CBUS_SOLN, 0,  sizeof(pf_cbus_soln),  0, 110},
 {'f', offsetof(pf_cbus_soln,Pgen),       sizeof(float),  20, 15, 7},
 {'f', offsetof(pf_cbus_soln,Qgen),       sizeof(float),  35, 15, 7},
 {'f', offsetof(pf_cbus_soln,Pload),      sizeof(float),  50, 15, 7},
 {'f', offsetof(pf_cbus_soln,Qload),      sizeof(float),  65, 15, 7},
 {'f', offsetof(pf_cbus_soln,Gshunt),     sizeof(float),  80, 15, 7},
 {'f', offsetof(pf_cbus_soln,Bshunt),     sizeof(float),  95, 15, 7},
},

{{CBUS, 0,  sizeof(pf_cbus),    0,    57},
 {'s', offsetof(pf_cbus,type),                    2,       0,  2, 0},
 {'s', offsetof(pf_cbus,owner),                   3,       3,  3, 0},
 {'s', offsetof(pf_cbus,name),                    8,       6,  8, 0},
 {'f', offsetof(pf_cbus,kv),              sizeof(float),  14,  4, 0},
 {'s', offsetof(pf_cbus,code_year),               2,      18,  2, 0},
 {'f', offsetof(pf_cbus,Pload),           sizeof(float),  20,  5, 0},
 {'f', offsetof(pf_cbus,Qload),           sizeof(float),  25,  5, 0},
 {'f', offsetof(pf_cbus,Gshunt),          sizeof(float),  30,  4, 0},
 {'f', offsetof(pf_cbus,Bshunt),          sizeof(float),  34,  4, 0},
 {'f', offsetof(pf_cbus,Pgen),            sizeof(float),  42,  5, 0},
 {'f', offsetof(pf_cbus,Qgen_Qmax),       sizeof(float),  47,  5, 0},
 {'f', offsetof(pf_cbus,Qmin),            sizeof(float),  52,  5, 0},
},

{{QCURVE, 0,  sizeof(pf_qcurve),  0,  78},
 {'s', offsetof(pf_qcurve,type),                      2,   0,  2, 0},
 {'s', offsetof(pf_qcurve,PU_code),                   2,   3,  2, 0},
 {'s', offsetof(pf_qcurve,active),                    1,   5,  1, 0},
 {'s', offsetof(pf_qcurve,bus_name),                  8,   6,  8, 0},
 {'f', offsetof(pf_qcurve,bus_kv),        sizeof(float),  14,  4, 0},
 {'f', offsetof(pf_qcurve,Pgen0),         sizeof(float),  18,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen1),         sizeof(float),  24,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen2),         sizeof(float),  30,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen3),         sizeof(float),  36,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen4),         sizeof(float),  42,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen5),         sizeof(float),  48,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen6),         sizeof(float),  54,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen7),         sizeof(float),  60,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen8),         sizeof(float),  66,  6, 0},
 {'f', offsetof(pf_qcurve,Pgen9),         sizeof(float),  72,  6, 0},
},

{{XDATA_SOLN, 0,  sizeof(pf_xdata_soln),    0,   156},
 {'l', offsetof(pf_xdata_soln,seg1_sch_units),      sizeof(long ),  20,  1, 0},
 {'l', offsetof(pf_xdata_soln,seg1_used_units),     sizeof(long ),  21,  1, 0},
 {'f', offsetof(pf_xdata_soln,seg1_mvar_per_unit),  sizeof(float),  22, 15, 7},
 {'l', offsetof(pf_xdata_soln,seg2_sch_units),      sizeof(long ),  37,  1, 0},
 {'l', offsetof(pf_xdata_soln,seg2_used_units),     sizeof(long ),  38,  1, 0},
 {'f', offsetof(pf_xdata_soln,seg2_mvar_per_unit),  sizeof(float),  39, 15, 7},
 {'l', offsetof(pf_xdata_soln,seg3_sch_units),      sizeof(long ),  54,  1, 0},
 {'l', offsetof(pf_xdata_soln,seg3_used_units),     sizeof(long ),  55,  1, 0},
 {'f', offsetof(pf_xdata_soln,seg3_mvar_per_unit),  sizeof(float),  56, 15, 7},
 {'l', offsetof(pf_xdata_soln,seg4_sch_units),      sizeof(long ),  71,  1, 0},
 {'l', offsetof(pf_xdata_soln,seg4_used_units),     sizeof(long ),  72,  1, 0},
 {'f', offsetof(pf_xdata_soln,seg4_mvar_per_unit),  sizeof(float),  73, 15, 7},
 {'l', offsetof(pf_xdata_soln,seg5_sch_units),      sizeof(long ),  88,  1, 0},
 {'l', offsetof(pf_xdata_soln,seg5_used_units),     sizeof(long ),  89,  1, 0},
 {'f', offsetof(pf_xdata_soln,seg5_mvar_per_unit),  sizeof(float),  90, 15, 7},
 {'l', offsetof(pf_xdata_soln,seg6_sch_units),      sizeof(long ), 105,  1, 0},
 {'l', offsetof(pf_xdata_soln,seg6_used_units),     sizeof(long ), 106,  1, 0},
 {'f', offsetof(pf_xdata_soln,seg6_mvar_per_unit),  sizeof(float), 107, 15, 7},
 {'l', offsetof(pf_xdata_soln,seg7_sch_units),      sizeof(long ), 122,  1, 0},
 {'l', offsetof(pf_xdata_soln,seg7_used_units),     sizeof(long ), 123,  1, 0},
 {'f', offsetof(pf_xdata_soln,seg7_mvar_per_unit),  sizeof(float), 124, 15, 7},
 {'l', offsetof(pf_xdata_soln,seg8_sch_units),      sizeof(long ), 139,  1, 0},
 {'l', offsetof(pf_xdata_soln,seg8_used_units),     sizeof(long ), 140,  1, 0},
 {'f', offsetof(pf_xdata_soln,seg8_mvar_per_unit),  sizeof(float), 141, 15, 7},
},

{{XDATA, 0,  sizeof(pf_xdata),    0,    80},
 {'s', offsetof(pf_xdata,type),                       2,   0,  2, 0},
 {'s', offsetof(pf_xdata,owner),                      3,   3,  3, 0},
 {'s', offsetof(pf_xdata,bus_name),                   8,   6,  8, 0},
 {'f', offsetof(pf_xdata,bus_kv),         sizeof(float),  14,  4, 0},
 {'s', offsetof(pf_xdata,rmt_name),                   8,  20,  8, 0},
 {'f', offsetof(pf_xdata,rmt_kv),         sizeof(float),  28,  4, 0},
 {'l', offsetof(pf_xdata,seg1_num_steps), sizeof(long ),  32,  1, 0},
 {'f', offsetof(pf_xdata,seg1_delta_mva), sizeof(float),  33,  5, 0},
 {'l', offsetof(pf_xdata,seg2_num_steps), sizeof(long ),  38,  1, 0},
 {'f', offsetof(pf_xdata,seg2_delta_mva), sizeof(float),  39,  5, 0},
 {'l', offsetof(pf_xdata,seg3_num_steps), sizeof(long ),  44,  1, 0},
 {'f', offsetof(pf_xdata,seg3_delta_mva), sizeof(float),  45,  5, 0},
 {'l', offsetof(pf_xdata,seg4_num_steps), sizeof(long ),  50,  1, 0},
 {'f', offsetof(pf_xdata,seg4_delta_mva), sizeof(float),  51,  5, 0},
 {'l', offsetof(pf_xdata,seg5_num_steps), sizeof(long ),  56,  1, 0},
 {'f', offsetof(pf_xdata,seg5_delta_mva), sizeof(float),  57,  5, 0},
 {'l', offsetof(pf_xdata,seg6_num_steps), sizeof(long ),  62,  1, 0},
 {'f', offsetof(pf_xdata,seg6_delta_mva), sizeof(float),  63,  5, 0},
 {'l', offsetof(pf_xdata,seg7_num_steps), sizeof(long ),  68,  1, 0},
 {'f', offsetof(pf_xdata,seg7_delta_mva), sizeof(float),  69,  5, 0},
 {'l', offsetof(pf_xdata,seg8_num_steps), sizeof(long ),  74,  1, 0},
 {'f', offsetof(pf_xdata,seg8_delta_mva), sizeof(float),  75,  5, 0},
},





{{COMM, 0, 120 , 0, 120},
 { 's', 0,                                          118,   1,118, 0},
},
{{ 2},
 { 's',  5,  6, 2,  7,0},
 { 's',  6,  7, 3,  4,0},
}
};

 
