C    @(#)comn34.inc	4.3 9/21/93
      common/msind/msub1(2),msub2(2),msub4(2)
      common /link34/ kpackt,kpkpct,kxname,kcor,kecst,kecsx,ktbl,
     1kslack,ntoto,ntotd,ntot,kbsknt,kzrecs
     2, cvcon,isgg,jphno,kecsy,ntota,mxng,mxnb
     3,ltott,ltot,ntot2o,ntot2t,ntotc,ntotm,ibr,kxtot,ntott
     4, jtie,kdtot,ntotb,kectbl,kecdta
     5, lsknt
      integer msub1,msub2,msub4
      integer kpackt,kpkpct,kxname,kcor,kecst,kecsx,ktbl,
     1 kslack,ntoto,ntotd,ntot,kbsknt,kzrecs
     2, isgg,jphno,kecsy,ntota,mxng,mxnb
     3, ltott,ltot,ntot2o,ntot2t,ntotc,ntotm,ibr,kxtot,ntott
     4, jtie,kdtot,ntotb,kectbl,kecdta
     5, lsknt
      real cvcon 
