C    @(#)param.inc	4.3 9/21/93

      common /param/ ddly, dt, endt, epz, ezp, pdly, tsim, toli,
     &               sater, angler, nmx, nmx2, matlim, matsz, iblim,
     &               ilim, bmva, to, nmxm5, nmxm4, indxm, frqbse,
     &               kmdcbs, kmdcbr, mfdep, mrelay, dtsj, dtsc

      integer nmx, nmx2, matlim, matsz, iblim, ilim, nmxm5, nmxm4,
     &        indxm, kmdcbs, kmdcbr, mfdep, mrelay
      real ddly, dt, endt, epz, ezp, pdly, tsim, toli, sater, angler,
     &     bmva, to, frqbse, dtsj, dtsc

