      integer VYMAX
      parameter (VYMAX = 25)
      common/vy1/vyalfa(VYMAX),vyar1(VYMAX),vyar2(VYMAX),vyar3(VYMAX),
     1           vyar4(VYMAX),vyar5(VYMAX),vyar6(VYMAX),vyk1(VYMAX),
     2           vypmax(VYMAX),vypmin(VYMAX),vyimax(VYMAX),
     3           vyimin(VYMAX),vygo(VYMAX),vybo(VYMAX),vygv(VYMAX),
     4           vyxint(VYMAX),vypint(VYMAX),vyhb1(VYMAX),vyhb2(VYMAX),
     5           vyhb3(VYMAX),vyhb4(VYMAX),vyhb5(VYMAX),vyaa(VYMAX),
     6           vyab(VYMAX),vyvb(VYMAX),vyvbo(VYMAX),vyil(VYMAX),
     7           vyilo(VYMAX),vyvb1(VYMAX),vyil1(VYMAX),vygtot(VYMAX),
     8           vybtot(VYMAX),vyamax(VYMAX),vyamin(VYMAX),
     9           vybmax(VYMAX),vybmin(VYMAX),vyalfo(VYMAX),vybv(VYMAX),
     *           vyalfi(VYMAX),ivypi(VYMAX),vyfreq(VYMAX),vyango(VYMAX)
