Elem e[]={
          { "MIFFile"               , MIFFILE      },
          { "ConditionCatalog"     , CONDITIONCATALOG},
          { "Condition"            , CONDITION    },
          { "CTag"                 , CTAG         },
          { "CState"               , CSTATE       },
          { "CShown"               , CSHOWN       },
          { "CHidden"              , CHIDDEN      },
          { "CStyle"               , CSTYLE       },
          { "CAsIs"                , CASIS        },
          { "CUnderline"           , CUNDERLINE   },
          { "CStrike"              , CSTRIKE      },
          { "COverline"            , COVERLINE    },
          { "CSeparation"          , CSEPARATION  },
          { "PgfCatalog"           , PGFCATALOG   },
          { "FontCatalog"          , FONTCATALOG  },
          { "Pgf"                  , PGF          },
          { "PgfTag"               , PGFTAG       },
          { "PgfUseNextTag"        , PGFUSENEXTTAG},
          { "PgfNextTag"           , PGFNEXTTAG   },
          { "PgfAlignment"         , PGFALIGNMENT },
          { "PgfFIndent"           , PGFFINDENT   },
          { "PgfLIndent"           , PGFLINDENT   },
          { "PgfRIndent"           , PGFRINDENT   },
          { "PgfTopSeparator"      , PGFTOPSEPARATOR},
          { "PgfBotSeparator"      , PGFBOTSEPARATOR},
          { "PgfPlacement"         , PGFPLACEMENT },
          { "Anywhere"             , ANYWHERE     },
          { "ColumnTop"            , COLUMNTOP    },
          { "PageTop"              , PAGETOP      },
          { "LPageTop"             , LPAGETOP     },
          { "RPageTop"             , RPAGETOP     },
          { "PgfSpBefore"          , PGFSPBEFORE  },
          { "PgfSpAfter"           , PGFSPAFTER   },
          { "PgfWithPrev"          , PGFWITHPREV  },
          { "PgfWithNext"          , PGFWITHNEXT  },
          { "PgfBlockSize"         , PGFBLOCKSIZE },
          { "PgfFont"              , PGFFONT      },
          { "PgfLineSpacing"       , PGFLINESPACING},
          { "Fixed"                , EMFIXED      }, 
          { "Proportional"         , PROPORTIONAL }, 
          { "Floating"             , FLOATING     }, 
          { "PgfLeading"           , PGFLEADING   },
	  { "PgfAutoNum"           , PGFAUTONUM   },
	  { "PgfNumFormat"         , PGFNUMFORMAT },
	  { "PgfNumberFont"        , PGFNUMBERFONT},
	  { "PgfNumAtEnd"          , PGFNUMATEND  },
	  { "PgfNumTabs"           , PGFNUMTABS   },
	  { "TabStop"              , TABSTOP      },
	  { "TSX"                  , TSX          },
	  { "TSType"               , TSTYPE       },
	  { "TSLeaderStr"          , TSLEADERSTR  },
	  { "TSDecimalChar"        , TSDECIMALCHAR},
	  { "PgfHyphenate"         , PGFHYPHENATE },
	  { "HyphenMaxLines"       , HYPHENMAXLINES},
	  { "HyphenMinPrefix"      , HYPHENMINPREFIX},
	  { "HyphenMinSuffix"      , HYPHENMINSUFFIX},
	  { "HyphenMinWord"        , HYPHENMINWORD},
	  { "PgfLetterSpace"       , PGFLETTERSPACE},
	  { "PgfMinWordSpace"      , PGFMINWORDSPACE},
	  { "PgfOptWordSpace"      , PGFOPTWORDSPACE},
	  { "PgfMaxWordSpace"      , PGFMAXWORDSPACE},
	  { "PgfLanguage"          , PGFLANGUAGE  },  
	  { "USEnglish"            , USENGLISH    },  
	  { "PgfCellAlignment"     , PGFCELLALIGNMENT},
	  { "Top"                  , TOP          },
	  { "Middle"               , MIDDLE       },
	  { "Bottom"               , BOTTOM       },
	  { "PgfCellMargins"       , PGFCELLMARGINS},
	  { "PgfCellLMarginFixed"  , PGFCELLLMARGINFIXED},
	  { "PgfCellTMarginFixed"  , PGFCELLTMARGINFIXED},
	  { "PgfCellRMarginFixed"  , PGFCELLRMARGINFIXED},
	  { "PgfCellBMarginFixed"  , PGFCELLBMARGINFIXED},

          { "Left"                 , LEFT         },
          { "Right"                , RIGHT        },
          { "Center"               , CENTER       },
          { "LeftRight"            , LEFTRIGHT    },
          { "Plain"                , PLAIN        },
          { "Italic"               , ITALIC       },
          { "Bold"                 , BOLD         },
          { "String"               , EMSTRING     },
          { "PgfFontStyle"         , PGFFONTSTYLE },
          { "PgfFontSize"          , PGFFONTSIZE  },
          { "Font"                 , FONT         },
          { "Units"                , UNITS        },
          { "Uin"                  , UIN          },
          { "Ucm"                  , UCM          },
          { "Umm"                  , UMM          },
          { "Upica"                , UPICA        },
          { "Upt"                  , UPT          },
          { "Udd"                  , UDD          },
          { "Ucc"                  , UCC          },
          { "Yes"                  , YES          },
          { "No"                   , NO           },
          { "<"                    , LT           },
          { ">"                    , GT           },
          { "FSeparation"          , FSEPARATION  },
          { "FFamily"              , FFAMILY      },
          { "FVar"                 , FVAR         },
          { "FTag"                 , FTAG         },
          { "FWeight"              , FWEIGHT      },
          { "FAngle"               , FANGLE       },
          { "FSize"                , FSIZE        },
          { "FPlain"               , FPLAIN       },
          { "FBold"                , FBOLD        },
          { "FItalic"              , FITALIC      },
          { "FUnderline"           , FUNDERLINE   },
          { "FOverline"            , FOVERLINE    },
          { "FStrike"              , FSTRIKE      },
          { "FSupScript"           , FSUPSCRIPT   },
          { "FSubScript"           , FSUBSCRIPT   },
          { "FChangeBar"           , FCHANGEBAR   },
          { "FOutline"             , FOUTLINE     },
          { "FShadow"              , FSHADOW      },
          { "FPairKern"            , FPAIRKERN    },
          { "FDoubleUnderline"     , FDOUBLEUNDERLINE},
          { "FNumericUnderline"    , FNUMERICUNDERLINE},
          { "FDX"                  , FDX          },
          { "FDY"                  , FDY          },
          { "FDW"                  , FDW          },
          { "Page"                 , PAGE         },
          { "PageType"             , PAGETYPE     },
          { "LeftMasterPage"       , LEFTMASTERPAGE},
          { "RightMasterPage"      , RIGHTMASTERPAGE},
          { "OtherMasterPage"      , OTHERMASTERPAGE},
          { "ReferencePage"        , REFERENCEPAGE},
          { "BodyPage"             , BODYPAGE     },
          { "HiddenPage"           , HIDDENPAGE   },
          { "Portrait"             , PORTRAIT     },
          { "Landscape"            , LANDSCAPE    },
          { "PageNum"              , PAGENUM      },
          { "PageTag"              , PAGETAG      },
          { "PageSize"             , PGESIZE      },
          { "PageOrientation"      , PGEORIENTATION},
          { "PageBackground"       , PAGEBACKGROUND},

          { "TextRectID"           , TEXTRECTID   },
          { "TextRect"             , TEXTRECT     },
          { "ID"                   , ID           },
          { "Pen"                  , PEN          },
          { "Fill"                 , FILL         },
          { "PenWidth"             , PENWIDTH     },
          { "Separation"           , SEPARATION   },
          { "Angle"                , ANGLE        },
          { "BRect"                , BRECT        },
          { "TRNext"               , TRNEXT       },
          { "TextFlow"             , TEXTFLOW     },
          { "TFTag"                , TFTAG        },
          { "TFAutoConnect"        , TFAUTOCONNECT},
          { "Para"                 , PARA         },
          { "PgfNumString"         , PGFNUMSTRING },
          { "ParaLine"             , PARALINE     },
          { "String"               , EMSTRING     },
          { "Char"                 , EMCHAR       },
          { "SoftHyphen"           , SOFTHYPHEN   },
          { "HardReturn"           , HARDRETURN   },
          { "EmDash"               , EMDASH       },
          { "Tab"                  , TAB          },

          { "Marker"               , MARKER       },
          { "MType"                , MTYPE        },
          { "MText"                , MTEXT        },
          { "MCurrPage"            , MCURRPAGE    },

          { "Notes"                , NOTES        },
          { "Variable"             , VARIABLE     },
          { "VariableName"         , VARIABLENAME },
          { "AFrames"              , AFRAMES      },
          { "AFrame"               , AFRAME       },
          { "Frame"                , FRAME        },
          { "ATbl"                 , ATBL         },
};
