enum { NO=0,YES=1,PGFALIGNMENT,PGFFINDENT,PGFLINDENT,PGFRINDENT,PGFFONT,
       PGFFONTSIZE,PGFFONTSTYLE,LEFT,CENTER,RIGHT,LEFTRIGHT,PLAIN,ITALIC,
       BOLD,LT,GT,UNITS,UIN,UCM,UMM,UPICA,UPT,UDD,UCC,PGFCATALOG,
       PGF,PGFTAG,PGFSPBEFORE,PGFSPAFTER,FFAMILY,FVAR,FWEIGHT,FANGLE,FSIZE,
       FPLAIN,FBOLD,FITALIC,FUNDERLINE,FOVERLINE,FSTRIKE,FSUPSCRIPT,
       FSUBSCRIPT,FCHANGEBAR,FOUTLINE,FSHADOW,FPAIRKERN,FTAG,
       FONTCATALOG,FONT,   /* # 50 */
       PAGE,PGFUSENEXTTAG,PGFNEXTTAG,PGFTOPSEPARATOR,
       PGFBOTSEPARATOR,PGFWITHPREV,PGFWITHNEXT,PGFBLOCKSIZE,PGFPLACEMENT,
       PGFLEADING,ANYWHERE,COLUMNTOP,PAGETOP,LPAGETOP,RPAGETOP,FDX,FDY,FDW,
       FDOUBLEUNDERLINE,FNUMERICUNDERLINE,FSEPARATION,PGFLINESPACING,
       PGFAUTONUM,PGFNUMATEND,PGFHYPHENATE,PGFLETTERSPACE,PGFNUMFORMAT,
       PGFNUMBERFONT,PGFNUMTABS,HYPHENMAXLINES,HYPHENMINPREFIX,
       HYPHENMINSUFFIX,HYPHENMINWORD,EMFIXED,PROPORTIONAL,FLOATING,
       PGFMINWORDSPACE,PGFOPTWORDSPACE,PGFMAXWORDSPACE,PGFLANGUAGE,
       PGFCELLALIGNMENT,PGFCELLMARGINS,PGFCELLLMARGINFIXED,PGFCELLTMARGINFIXED,
       PGFCELLRMARGINFIXED,PGFCELLBMARGINFIXED,USENGLISH,TOP,MIDDLE,BOTTOM, /*#100*/

       TABSTOP,TSX,TSTYPE,TSLEADERSTR,TSDECIMALCHAR,MIFFILE,CONDITIONCATALOG,
       CONDITION,CTAG,CSTATE,CSTYLE,CSEPARATION,CSHOWN,CHIDDEN,CASIS,CUNDERLINE,
       CSTRIKE,COVERLINE,PAGETYPE,PAGENUM,PAGETAG,PGESIZE,PGEORIENTATION,
       PAGEBACKGROUND,LEFTMASTERPAGE,RIGHTMASTERPAGE,OTHERMASTERPAGE,
       REFERENCEPAGE,BODYPAGE,HIDDENPAGE,PORTRAIT,LANDSCAPE,ANGLE,BRECT,ID,
       PEN,FILL,PENWIDTH,SEPARATION,TRNEXT,TEXTRECT,TEXTFLOW,PARA,TEXTRECTID,
       PARALINE,EMSTRING,EMCHAR,SOFTHYPHEN,HARDRETURN,EMDASH, /* # 150 */
       TAB,PGFNUMSTRING,MARKER,MTYPE,MTEXT,MCURRPAGE,TFTAG,TFAUTOCONNECT,
       NOTES,VARIABLE,VARIABLENAME,AFRAMES,FRAME,ATBL,AFRAME
};
/* Elem structure holds ASCII keyword name and integer 'token' pairs */
typedef struct {
  char key[25];
  int  data;
} Elem;
/* Ucm structure holds start and length pairs of user comments */
typedef struct {
  long start;  
  long len; 
} Ucm;
#define UCM_DIR_MAX 512
