c ********** start of cvdata.inc *********

c      Full Arc Steam Valve Nonlinear Gain (Ngv = 101)
       data totalpts(1) /5/,
     &      inpt(1,1) /0.00/, outpt(1,1) /0.00/,  
     &      inpt(1,2) /0.40/, outpt(1,2) /0.75/,  
     &      inpt(1,3) /0.50/, outpt(1,3) /0.91/,  
     &      inpt(1,4) /0.60/, outpt(1,4) /0.98/,  
     &      inpt(1,5) /1.00/, outpt(1,5) /1.00/  

c      Hydro Gate Nonlinear Gain (Ngv = 102)
       data totalpts(2) /6/,
     &      inpt(2,1) /0.08/, outpt(2,1) /0.00/,  
     &      inpt(2,2) /0.30/, outpt(2,2) /0.20/,  
     &      inpt(2,3) /0.80/, outpt(2,3) /0.80/,  
     &      inpt(2,4) /0.90/, outpt(2,4) /0.90/,  
     &      inpt(2,5) /1.00/, outpt(2,5) /0.96/,  
     &      inpt(2,6) /1.20/, outpt(2,6) /1.00/  

c ********** end of cvdata.inc *********
