C    %W% %G%
      common /titles/ relay,remote,series,capac,load,repr,shed,net,
     1                machn,datx,blnk10,swdata,pfdate,xend,direct,
     2                currnt,pfcase,savin,savout,swdate,swcase,
     3                svdate
      character*10 relay,remote,series,capac,
     4             load,repr,shed,net,machn,datx,blnk10,
     4             swdata,pfdate,xend,direct,currnt,pfcase,
     4             savin,savout,swdate,swcase,svdate
