*BEGIN ARRFD
      DIMENSION ARRAY(40),A(40)
       EQUIVALENCE        (ARRAY(1), VRMAX),(ARRAY(2), VRMIN),
     1 (ARRAY(3),  VREF), (ARRAY(4),EFDMAX),(ARRAY(5),   CKI),
     2 (ARRAY(6),   HBR), (ARRAY(7),  CCKP),(ARRAY(8),   CKA),
     3 (ARRAY(9),    DR), (ARRAY(10),  CKC),(ARRAY(11), HBF),
     4 (ARRAY(12),   DF),(ARRAY(13),DK),(ARRAY(14),    DE),
     5 (ARRAY(15),  CKE), (ARRAY(24),   CKPI),
     6 (ARRAY(16),   VAO),(ARRAY(17),   VBO),(ARRAY(18),   VCO),
     7 (ARRAY(19), VINO),(ARRAY(20),    XL),(ARRAY(21),  RCEX),
     8 (ARRAY(22),   XCEX),(ARRAY(23),  CKPR),(ARRAY(25),    DA),
     9 (ARRAY(26),   HBA),(ARRAY(27),   HBE),(ARRAY(28), THETA),
     * (ARRAY(29),   EFD),(ARRAY(30),   A1),(ARRAY(31),     A2),
     * (ARRAY(32),    A3),(ARRAY(33),   VIO),(ARRAY(34),  BNF)
