*BEGIN ARRFG
      DIMENSION ARRAY(40),A(40)
       EQUIVALENCE        (ARRAY(1), VRMAX),(ARRAY(2), VRMIN),
     1 (ARRAY(3),  VREF), (ARRAY(4),EFDMAX),(ARRAY(5),EFDMIN),
     2 (ARRAY(6),   HBR), (ARRAY(7),   HBF),(ARRAY(8),   CKA),
     3 (ARRAY(9),    DR), (ARRAY(10),  CKC),(ARRAY(11),VIMAX),
     4 (ARRAY(12),VIMIN),(ARRAY(13),VA),(ARRAY(14),VAO),
     5 (ARRAY(15),  HCB), (ARRAY(24),   CKF),
     6 (ARRAY(16),   CKJ),(ARRAY(17),    DB),(ARRAY(18),    DC),
     7 (ARRAY(19),    DF),(ARRAY(20),    DK),(ARRAY(21),  RCEX),
     8 (ARRAY(22),   VRO),(ARRAY(23),  XCEX),(ARRAY(25),    DA),
     9 (ARRAY(26),   HBA),(ARRAY(27),   VCO),(ARRAY(28), THETA),
     * (ARRAY(29),   EFD),(ARRAY(30),    A1),(ARRAY(31),    A2),
     * (ARRAY(32),  CKPI),(ARRAY(33),   SLPO),(ARRAY(34),  BNF)
