*BEGIN ARRFE
      DIMENSION ARRAY(40),A(40)
       EQUIVALENCE         (ARRAY(1),  VRMAX), (ARRAY(2),  VRMIN),
     1 (ARRAY(3),   VREF), (ARRAY(4),  ESATX), (ARRAY(5),  CSATX),
     2 (ARRAY(6),    HBR), (ARRAY(7),    CKE), (ARRAY(8),    CKV),
     3 (ARRAY(9),     DR), (ARRAY(10),   SE2),
     4
     5 (ARRAY(15),   HCB),
     6 (ARRAY(18),   VRH), (ARRAY(19),   HBE), (ARRAY(20),    DE),
     7 (ARRAY(21),  RCEX), (ARRAY(22),    VR), (ARRAY(23),  XCEX),
     8 (ARRAY(24),   VAO), (ARRAY(25),    DA), (ARRAY(26),   HBA),
     9 (ARRAY(27),   VCO), (ARRAY(28),   SLP), (ARRAY(29),   EFD),
     * (ARRAY(30),  VAI1), (ARRAY(31),EFDMIN), (ARRAY(32),EFDMAX),
     * (ARRAY(33),  CKAP)
