C      -            bpapds.inc 
* * ******************************************************************  
* * ******************************************************************  
* ! *                                                                *  
* ! *                                                                *  
* ! *                                                                *  
* ! *                                                                *  
* ! *  PUBLIC_DOMAIN SOFTWARE  1988, 1989, 1990 BY                   *  
* ! *  Bonneville Power Administration (BPA), Dept. of Energy,       *  
* ! *  U. S. Government                                              *  
* ! *  P. O. Box 3621         Mail Stop EOHB                         *  
* ! *  Portland, Or. 97208                                           *  
* ! *                                                                *  
* ! *                                                                *  
* ! *  This subroutine has been developed by BPA for it's own use on *  
* ! *  Digital Equipment Corporation (DEC) VAX/VMS systems. As such, *  
* ! *  BPA makes no warranty or representation, expressed or implied,*  
* ! *  with respect to the accuracy, completeness, or usefulness of  *  
* ! *  this software.                                                *  
* ! *                                                                *  
* ! *  Under the Freedom of Information Act, BPA has placed this     *  
* ! *  subroutine in the Public Domain and you may incorporate it    *  
* ! *  into other programs and freely distribute it as long as this  *  
* ! *  notice is not removed.                                        *  
* ! *                                                                *  
* ! *                                                                *  
* ! *                                                                *  
* ! *                                                                *  
* * ******************************************************************  
* * ******************************************************************  
*                                                                       
c   -                   end of bpapds.inc                               

