c     -                      files.inc
c  New on May/05/92 by DEM
c  Revised on Jun/09/92 by DEM
C  Added postscript master file Oct 13,94 dms
      COMMON /FILES/ SAVIFL,SAVOFL,SOLFL,PLTFL,PRTFL,AUXFL,BSEFL,
     +  CTRLFL,FILEFL,DBGIFL,DBGOFL,POSTMSTR
        CHARACTER SAVIFL*60,SAVOFL*60,SOLFL*60,PLTFL*60,PRTFL*60
        CHARACTER AUXFL*60,BSEFL*60,CTRLFL*60,FILEFL*60
        CHARACTER DBGIFL*60,DBGOFL*60,POSTMSTR*60
c     -                   end of files.inc
