
      common /out512/ bmva, exmax, exmin, ibdatt, ibgd, icnt2, igdatt,
     &       igecs, iggd, igrp, ildat, ilgd, imod, iref, istrt, jphno,
     &       kbecs, kecsol, kecsym, kgecs, klecs, kmbrch, kmbus, knext,
     &       ksave, kx2nec, kxtot, ldc, ldco, ltoto, ltott, maxcyc,
     &       namecs, nmxp, noline(8), nop, nskp, ntot, ntot2, ntot2t,
     &       ntotc, ntotm, ntott, tmaxp, tref, ldc1, nopz, itbld, tstrt,
     &       nsymskp
      integer ibdatt, ibgd, icnt2, igdatt,
     &       igecs, iggd, igrp, ildat, ilgd, imod, iref, istrt, jphno,
     &       kbecs, kecsol, kecsym, kgecs, klecs, kmbrch, kmbus, knext,
     &       ksave, kx2nec, kxtot, ldc, ldco, ltoto, ltott, maxcyc,
     &       namecs, nmxp, noline, nop, nskp, ntot, ntot2, ntot2t,
     &       ntotc, ntotm, ntott, ldc1, nopz, itbld, nsymskp
      real bmva, exmax, exmin, tref, tstrt, tmaxp

c    nsymskp -  symbols are plotted every nsymskp-th point. Default = 1 
