      integer VYMMAX
      parameter (VYMMAX = 25)
      common/vym/ivymsw(VYMMAX),vymca(VYMMAX),vymcb(VYMMAX),
     1       vymcd(VYMMAX),vymce(VYMMAX),vymar(VYMMAX),vymare(VYMMAX),
     2       vymarf(VYMMAX),vymarg(VYMMAX),vymarh(VYMMAX),
     3       vymab(VYMMAX),vymdc(VYMMAX),vymhbe(VYMMAX),vymhbf(VYMMAX),
     4       vymhbg(VYMMAX),vymbo(VYMMAX),vyma1(VYMMAX),vyma2(VYMMAX),
     5       vymimx(VYMMAX),vymimn(VYMMAX),vymmd(VYMMAX),vymdo(VYMMAX),
     6       vymp(VYMMAX),vympo(VYMMAX),ivymb1(VYMMAX),ivymb2(VYMMAX),
     7       vymgij(VYMMAX),vymgii(VYMMAX),vymbij(VYMMAX),
     8       vymbii(VYMMAX),vymhb4(VYMMAX),vymck(VYMMAX),vymcc(VYMMAX),
     9       vymx5(VYMMAX),vymx4(VYMMAX),vymx3(VYMMAX)
