C
        common /sin001/ tolpnt(5), limpnt(10), debpnt(7), conpnt(13),
     &                  itepnt(4), lsin, lsoli, ltol, llim, ldeb, 
     &                  lcon, rad
 
        integer tolpnt, limpnt, debpnt, conpnt, itepnt
 
        common /sin002/ soldic(4), debdic(8), toldic(6), limdic(12),
     1                  condic(13), sindic(21)
 
        character*10 sindic, soldic, toldic, limdic, condic, debdic
C
