*BEGIN ARRFH
      DIMENSION ARRAY(40),A(40)
       EQUIVALENCE         (ARRAY(1),  VAMAX), (ARRAY(2),  VAMIN),
     1 (ARRAY(3),   VREF), (ARRAY(4),  ESATX), (ARRAY(5),  CSATX),
     2 (ARRAY(6),    HBR), (ARRAY(7),    CKE), (ARRAY(8),    CKA),
     3 (ARRAY(9),     DR), (ARRAY(10),   CFDO), (ARRAY(11),   CKF),
     4 (ARRAY(12),    DF), (ARRAY(13),   VLV), (ARRAY(14),   CKN),
     5 (ARRAY(15),   CKR), (ARRAY(16),   CKC), (ARRAY(17),    DB),
     6 (ARRAY(18),    DC), (ARRAY(19),   EFDN), (ARRAY(20),    DE),
     7 (ARRAY(21),  RCEX), (ARRAY(22),    DK), (ARRAY(23),  XCEX),
     8 (ARRAY(24),    VAIO), (ARRAY(25),    DA), (ARRAY(26),   HBA),
     9 (ARRAY(27),   VCO), (ARRAY(28),     HBF), (ARRAY(29),   EFD),
     * (ARRAY(30),   CKD), (ARRAY(31),  DK1), (ARRAY(32),EFDMAX),
     * (ARRAY(33),   VEPO), (ARRAY(34),   HCB), (ARRAY(35),   HBE),
     * (ARRAY(36),    DEP), (ARRAY(37),BPRIM), (ARRAY(38),   VEO),
     * (ARRAY(39),  CKAP), (ARRAY(40),  CKEP)
