 
      integer BSTYP_B , BSTYP_BE, BSTYP_BS, BSTYP_BC, BSTYP_BD, 
     1        BSTYP_BV, BSTYP_BQ, BSTYP_BG, BSTYP_BO, BSTYP_BT,
     2        BSTYP_BX, BSTYP_BM, BSTYP_BF
     3       , BSTYP_BJ, BSTYP_BK, BSTYP_BL
c *** not used, but leave defined ***
c     3       , bstyp_BJ, bstyp_BK, bstyp_BL

      parameter ( BSTYP_B  = 1 )
      parameter ( BSTYP_BE = 2 )
      parameter ( BSTYP_BS = 3 )
      parameter ( BSTYP_BC = 4 )
      parameter ( BSTYP_BD = 5 )
      parameter ( BSTYP_BV = 6 )
      parameter ( BSTYP_BQ = 7 )
      parameter ( BSTYP_BG = 8 )
      parameter ( BSTYP_BO = 9 )
      parameter ( BSTYP_BT = 10 )
      parameter ( BSTYP_BX = 11 )
      parameter ( BSTYP_BM = 12 )
      parameter ( BSTYP_BF = 13 )

c *** not used, but leave defined ***
      parameter ( BSTYP_BJ = 14 )
      parameter ( BSTYP_BK = 15 )
      parameter ( BSTYP_BL = 16 )

