
      common  /lin_com/ fbe(20), fbed(20), fke(20), fked(20), PI,
     &                  fspac, corchk, valu1, valu7, valu8, valu9, 
     &                  valu10, valu11, valu12, valu13, unity, onehaf, 
     &                  onetrd , tenm6, switch, aaa1, aaa2, sqrt2, 
     &                  fmipkm,  finpcm, ftpm, lphase, lphpl1, lphd2, 
     &                  nthalf,  kful, metrik,  kparam, kcirct, nbundl,
     &                  iprsup, lunit6         

