
      common /ecvar/ dptot, dqtot, dttot, datot, ddtot, kownt, kownta, 
     &               kowntb, kowntc, kowntd, idswa, idswc, idswb,
     &               iasw, itsw, idcsw, koptsw, p1sked, ntopt, ntotx, 
     &               ngen, ntot11, ittot, qpen, karslk, ntbxtr, nntyp9, 
     &               nltc, nqpen ,ncvrt, nsen, vpen, ntotdc, ltotdc,
     &               nvpen ,ntxtie, npctvr, nldc, idckt, nckt(16)

c***kln  Single to double precision
c
	double precision dptot, dqtot, dttot, datot, ddtot
c
	integer kownt, kownta, kowntb, kowntc, kowntd, idswa, idswc, 
     &          idswb, iasw, itsw, idcsw, koptsw, ntopt, ntotx, ngen,
     &          ntot11, ittot, karslk, ntbxtr, nntyp9, nltc, nqpen,
     &          ncvrt, nsen, ntotdc, ltotdc, nvpen, ntxtie, npctvr,
     &          nldc, idckt, nckt
c
	real    p1sked, qpen, vpen
c
