C
        common /ordsta/ ordltc, ordtbx, ordcap, ordvlt, orddc, ordtie,
     &                  ordymx
        integer ordltc, ordtbx, ordcap, ordvlt, orddc, ordtie, ordymx
C
C       ordltc = 1/2: TRAN is in external/internal order
C       ordtbx = 1/2: TBX is in external/internal order
C       ordcap = 1/2: CAPCOR is in external/internal order
C       ordvlt = 1/2: E, F are in external/internal order
C       orddc  = 1/2: DC is in external/internal order
C       ordtie = 1/2: AREA, TIE are in external/internal order
C       ordymx = 1/2: Y-matrix is in external/internal order
C
