











                                       *******************************************************
                                       *                                                     *
                                       *                                                     *
                                       *     EXTENDED TRANSIENT-MIDTERM STABILITY PROGRAM    *
                                       *     ============================================    *
                                       *                                                     *
                                       *                      (ETMSP)                        *
                                       *                                                     *
                                       *                                                     *
                                       *            VERSION 3.10  RELEASE 93/06/15           *
                                       *                     LEVEL OHV3-00                   *
                                       *                                                     *
                                       *                JOINTLY DEVELOPED BY                 *
                                       *                                                     *
                                       *                    ONTARIO HYDRO                    *
                                       *                700 UNIVERSITY AVENUE                *
                                       *              TORONTO, ONTARIO,  CANADA              *
                                       *                                                     *
                                       *                         AND                         *
                                       *                                                     *
                                       *          ELECTRIC POWER RESEARCH INSTITUTE          *
                                       *                3412  HILLVIEW AVENUE                *
                                       *                PALO ALTO, CALIFORNIA                *
                                       *                                                     *
                                       *                                                     *
                                       *                                                     *
                                       *          WARNING AND ERROR MESSAGES REPORT          *
                                       *          =================================          *
                                       *                                                     *
                                       *               DATE OF RUN:  25-OCT-93               *
                                       *                                                     *
                                       * COPYRIGHT @(1993) ELECTRIC POWER RESEARCH INSTITUTE *
                                       *                 ALL RIGHTS RESERVED                 *
                                       *******************************************************

1  WARNING AND ERROR MESSAGES REFORT                                                                                   PAGE:   1

                                                         MISMATCH CHECK
                                                         ==============
 WARNING: THE MISMATCH AT THE FOLLOWING BUSES EXCEEDS 0.05 P.U. . THE USER IS URGED TO CHECK THE CONVERGENCE OF THE LOAD
           FLOW, THE LOADFLOW DATA AND DYNAMIC DATA ASSOCIATED WITH THESE BUSES. LOW IMPEDANCE LINES OF LESS THAN 0.005 P.U.
          ARE A LIKELY CAUSE OF THESE MISMATCHES, IN WHICH CASE THEY CAN BE IGNORED.

  BUS#   BUS NAME    INT#   GRBUS   GIBUS     PDG     PQG     CDL     CQL     BMW     BMX     PDF     QDF   EREAL   EIMAG
  ---- ------------  ----   -----   -----   -----   -----   -----   -----   -----   -----   -----   -----   -----   -----


                                                         * * * NO MISMATCH * * *

