mv arease~1.u areaselect.u
mv pf_des~1.u pf_descrip.u
mv networ~1.u networkedt.u
mv system~1.u systemtest.u
mv acbusf~1.u acbusform.u
mv acline~1.u aclineform.u
mv dcbusf~1.u dcbusform.u
mv dcline~1.u dclineform.u
mv equivf~1.u equivform.u
mv ipfrep~1.u ipfreport.u
mv debug_~1.u debug_dmgr.u
mv ipcwin~1.u ipcwindow.u
mv linezc~1.u linezcalc.u
mv report~1.u reportmenu.u
mv system~1.u systemtest.u
